# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation

#
# examples/librpmem/fibonacci/Makefile -- build the fibonacci example
#
PROGS = fibonacci

LIBS = -lrpmem -lpmem -pthread -lfabric

include ../../Makefile.inc

fibonacci: fibonacci.o
